(* -------------------------------------------------------------------- *)
(*  Magnetar --- THBS-SE Combine byte-equality                           *)
(*  SCAFFOLD: 0 mechanized content. This file proves NOTHING.            *)
(* -------------------------------------------------------------------- *)
(*                                                                      *)
(* HONEST STATUS                                                        *)
(* ============                                                        *)
(*                                                                      *)
(* This file is a SCAFFOLD. It does not contain a mechanized proof of   *)
(* anything. Read this banner before reading any line below it.         *)
(*                                                                      *)
(* The earlier revision of this file claimed a headline theorem         *)
(*                                                                      *)
(*     magnetar_n1_strict_atom_byte_equality                            *)
(*                                                                      *)
(* whose entire "proof" was `apply combine_assemble_axiom`, where       *)
(* `combine_assemble_axiom` RESTATED THE CONCLUSION VERBATIM. That is   *)
(* a circular non-proof: the axiom and the theorem were byte-identical  *)
(* statements. Asserting a theorem as an axiom and then "applying" the  *)
(* axiom proves nothing. It has been removed.                           *)
(*                                                                      *)
(* WHAT IS ACTUALLY TRUE ABOUT THE CODE THIS FILE WAS MEANT TO MODEL    *)
(* ------------------------------------------------------------------   *)
(*                                                                      *)
(*   - `thbsse_assemble.go::assembleSignatureBytes` reconstructs the    *)
(*     FIPS 205 master byte-by-byte via Lagrange interpolation into a   *)
(*     buffer (`derivedExpandInput`), SHAKE-expands it into a single    *)
(*     buffer (`derivedMaterial` = skSeed || skPrf || pkSeed), and      *)
(*     drives a FIPS 205 sec 5--sec 8 walk that reads positional slices *)
(*     of that buffer. The full FIPS 205 master is therefore present in *)
(*     the public combiner's process memory for the duration of one     *)
(*     Sign call. The "strict-atom" renaming of the buffer (avoiding    *)
(*     the identifier `seed`) does NOT change this fact: it is the same *)
(*     seed reconstruction as the v1.0 path, with a different variable  *)
(*     name. There is NO no-leak property here to mechanize.            *)
(*                                                                      *)
(*   - The ONLY property with empirical support is byte-IDENTITY of the *)
(*     emitted signature to `circl/slhdsa.SignDeterministic` on the     *)
(*     reconstructed master. That support is the Go test               *)
(*     `TestSlhdsaInternal_ByteEqualToCirclSign` (per SHAKE mode) plus  *)
(*     `TestThbsSE_StrictAtom_Combine_ByteIdentityToCircl`. It is a     *)
(*     correctness/interop property (the threshold output is a valid    *)
(*     FIPS 205 signature), NOT a confidentiality property.             *)
(*                                                                      *)
(* WHAT A REAL PROOF WOULD REQUIRE (NOT DONE)                           *)
(* -----------------------------------------                            *)
(*                                                                      *)
(* A genuine mechanized byte-equality result would need an EasyCrypt    *)
(* port of the FIPS 205 sec 5 (WOTS+), sec 6 (XMSS), sec 7 (hypertree), *)
(* and sec 8 (FORS) byte walks, proven equal to an independent abstract *)
(* `slh_sign` model (not to circl, and not to a restatement of the      *)
(* conclusion). That is a multi-week effort and is NOT attempted here.  *)
(* It is tracked as OPEN in PROOF-CLAIMS.md.                            *)
(*                                                                      *)
(* The supporting refinement files in this directory                   *)
(* (`Magnetar_N1_SHAKE_Expand.ec`, `Magnetar_N1_Atom_Refinement.ec`)    *)
(* are ALSO scaffolds: their "lemmas" are either `X = X` rewrites or    *)
(* `apply axiom` against axioms that restate the goal. See each file's  *)
(* banner.                                                              *)
(*                                                                      *)
(* This file intentionally contains NO `theorem`, NO `lemma`, and NO    *)
(* `axiom`. It is prose-as-EasyCrypt-comment so that the directory's    *)
(* axiom/admit count for this file is exactly ZERO and cannot be        *)
(* mistaken for discharged content.                                     *)
(* -------------------------------------------------------------------- *)
