(* -------------------------------------------------------------------- *)
(*  Magnetar --- PVSS-DKG setup                                          *)
(*  SCAFFOLD: 0 mechanized content. This file proves NOTHING.            *)
(* -------------------------------------------------------------------- *)
(*                                                                      *)
(* HONEST STATUS                                                        *)
(* ============                                                        *)
(*                                                                      *)
(* This file is a SCAFFOLD. The earlier revision declared three         *)
(* "theorems":                                                          *)
(*                                                                      *)
(*   - pvss_dkg_secrecy        --- conclusion `... true`, by `trivial`. *)
(*   - pvss_dkg_correctness    --- by `admit`.                          *)
(*   - pvss_dkg_wire_compat    --- conclusion `X = X`, by `trivial`.    *)
(*   - pvss_dkg_composition... --- conclusion `true`, by `trivial`.     *)
(*                                                                      *)
(* A lemma whose conclusion is `true` or `X = X` proves nothing about   *)
(* the construction; `admit` discharges nothing. All have been removed. *)
(*                                                                      *)
(* THE SECRECY CLAIM WAS NOT ONLY UNPROVEN --- IT WAS FALSE FOR THE     *)
(* CODE AS WRITTEN                                                       *)
(* ------------------------------------------------------------------   *)
(*                                                                      *)
(* The "secrecy theorem" asserted that an adversary controlling (t-1)   *)
(* parties learns nothing about the master M = sum_i m_i. But the DKG   *)
(* reference path (`pvss_dkg.go`) historically ran in OPEN-REVEAL mode: *)
(* `RunDKGSimulation` called `RevealMsg()` for EVERY party              *)
(* unconditionally, and `RevealMsg()` publishes `PolyCoeffs[b][0] =     *)
(* m_i[b]` --- the constant term, i.e. the contribution itself. With    *)
(* every m_i public, M = sum_i m_i is reconstructible by ANY observer,  *)
(* not merely by t-1 colluding insiders. A secrecy proof about code     *)
(* that broadcasts the secret is meaningless.                           *)
(*                                                                      *)
(* The production DKG default has since been changed to                 *)
(* COMPLAINT-CONDITIONAL reveal (`RunDKG`): a party publishes its       *)
(* coefficients ONLY against a recorded complaint; an honest run emits  *)
(* NO constant-term reveal. The open-reveal entry point is retained     *)
(* behind a loud TEST-ONLY barrier (`RunDKGSimulationOpenReveal`) that  *)
(* cannot be reached from the production constructor. See               *)
(* `pvss_dkg.go` and `TestPVSS_DKG_ProductionTranscriptHidesMaster`.    *)
(*                                                                      *)
(* Even with the code fixed, the secrecy statement remains UNPROVEN     *)
(* here: it reduces to byte-wise Shamir information-theoretic secrecy   *)
(* over GF(257), which is a standard textbook result but is NOT         *)
(* mechanized in this file (the prior `shamir_uniform_view` axiom did   *)
(* not even constrain the constant term --- its body was a vacuous      *)
(* existential). Mechanizing it is OPEN; tracked in PROOF-CLAIMS.md.    *)
(*                                                                      *)
(* WHAT HAS EMPIRICAL SUPPORT (Go tests, NOT proofs)                    *)
(* ------------------------------------------------                     *)
(*                                                                      *)
(*   - Wire-compat between the dealerless and dealer share envelopes:   *)
(*     `TestPVSS_DKG_ByteCompatWithDealerPath`.                         *)
(*   - t-1 corrupt parties cannot recover the master from their         *)
(*     partial-sum view (complaint-conditional path):                   *)
(*     `TestPVSS_DKG_AdversarialReveals`.                               *)
(*   - Production transcript does not reveal sum m_i:                    *)
(*     `TestPVSS_DKG_ProductionTranscriptHidesMaster`.                  *)
(*                                                                      *)
(* These are tests, not mechanized theorems.                            *)
(*                                                                      *)
(* This file intentionally declares no `theorem`, no `lemma`, and no    *)
(* `axiom`; its axiom/admit count is exactly ZERO.                      *)
(* -------------------------------------------------------------------- *)
